Front\FrontBundle\Entity\Keyword:
  type: entity
  table: keyword
  repositoryClass: Front\FrontBundle\Repository\KeywordRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    keyword:
      type: string
      length: 100
      fixed: false
      nullable: true
    lastTrack:
      type: date
      nullable: true
      column: last_track
    added:
      type: datetime
      nullable: true
  manyToOne:
    project:
      targetEntity: Project
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        project_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
