Front\FrontBundle\Entity\PageRanking:
  type: entity
  table: page_ranking
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    googleRank:
      type: integer
      unsigned: false
      nullable: true
      column: google_rank
    alexaRank:
      type: integer
      unsigned: false
      nullable: true
      column: alexa_rank
    checkDate:
      type: date
      nullable: true
      column: check_date
  manyToOne:
    project:
      targetEntity: Project
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        project_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
