Front\FrontBundle\Entity\ProjectCategory:
  type: entity
  table: project_category
  repositoryClass: Front\FrontBundle\Repository\ProjectCategoryRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    categoryName:
      type: string
      length: 250
      fixed: false
      nullable: true
      column: category_name
    isGeneric:
      type: integer
      unsigned: false
      nullable: true
      column: is_generic
  manyToOne:
    user:
      targetEntity: User
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        user_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
