Front\FrontBundle\Entity\Uptime:
  type: entity
  table: uptime
  repositoryClass: Front\FrontBundle\Repository\UptimeRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    siteStatus:
      type: string
      length: 5
      fixed: false
      nullable: true
      column: site_status
    checkDate:
      type: datetime
      nullable: true
      column: check_date
  manyToOne:
    project:
      targetEntity: Project
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        project_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
