Front\FrontBundle\Entity\UserSuggestions:
  type: entity
  table: user_suggestions
  repositoryClass: Front\FrontBundle\Repository\UserSuggestionsRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    logMessage:
      type: string
      length: 5000
      fixed: false
      nullable: true
      column: log_message
    added:
      type: datetime
      nullable: true
  lifecycleCallbacks: {  }
