BackendBackendBundle_login:
    pattern:  /login
    defaults: { _controller: BackendBackendBundle:Login:login }

BackendBackendBundle_logout:
    pattern:  /logout
    defaults: { _controller: BackendBackendBundle:Login:logout }

BackendBackendBundle_user:
    pattern:  /
    defaults: { _controller: BackendBackendBundle:User:index }
