BackendBackendBundle_login:
    pattern:  /login
    defaults: { _controller: BackendBackendBundle:Login:login }

BackendBackendBundle_logout:
    pattern:  /logout
    defaults: { _controller: BackendBackendBundle:Login:logout }

###  USER  ###
BackendBackendBundle_user:
    pattern:  /users
    defaults: { _controller: BackendBackendBundle:User:index }

BackendBackendBundle_user_actions:
    pattern:  /users-actions
    defaults: { _controller: BackendBackendBundle:User:userActions }

BackendBackendBundle_user_charts:
    pattern:  /users-charts
    defaults: { _controller: BackendBackendBundle:User:userCharts }
    
###  PROJECTS ###
BackendBackendBundle_project_stats:
    pattern:  /project-stats
    defaults: { _controller: BackendBackendBundle:Project:index }
    
### trial domains  ###
BackendBackendBundle_trial_domains:
    pattern:  /trial-domains
    defaults: { _controller: BackendBackendBundle:TrialDomains:index }
    
### payments  ###
BackendBackendBundle_all_payments:
    pattern:  /payments
    defaults: { _controller: BackendBackendBundle:Payments:index }
    
### cron watcher  ###
BackendBackendBundle_cron_watcher:
    pattern:  /cron-watcher
    defaults: { _controller: BackendBackendBundle:CronWatcher:index }

BackendBackendBundle_cron_profile:
    pattern:  /cron-profile
    defaults: { _controller: BackendBackendBundle:CronWatcher:cronProfile }

