BackendBackendBundle_login:
    pattern:  /login
    defaults: { _controller: BackendBackendBundle:Login:login }

BackendBackendBundle_logout:
    pattern:  /logout
    defaults: { _controller: BackendBackendBundle:Login:logout }

###  USER
BackendBackendBundle_user:
    pattern:  /users
    defaults: { _controller: BackendBackendBundle:User:index }

BackendBackendBundle_user_actions:
    pattern:  /users-actions
    defaults: { _controller: BackendBackendBundle:User:userActions }
