parameters:
#    backend_backend.example.class: Backend\BackendBundle\Example

services:
#    backend_backend.example:
#        class: %backend_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
